# Generated by Django 4.2.25 on 2025-10-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman.salesman')),
            ],
        ),
    ]
