# Generated by Django 4.2.25 on 2025-10-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0002_creditrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman.phonenumber')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesman.salesman')),
            ],
        ),
    ]
