# Generated by Django 4.2.25 on 2025-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0003_phonenumber_credittransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted')], max_length=20),
        ),
    ]
