# Generated by Django 4.2.25 on 2025-10-22 15:40

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0004_alter_creditrequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='state',
            field=django_fsm.FSMField(choices=[('requested', 'Requested'), ('accepted', 'Accepted')], default='requested', max_length=50),
        ),
    ]
