# Generated by Django 4.2.25 on 2025-10-22 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0005_alter_creditrequest_amount_alter_creditrequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
