# Generated by Django 4.2.25 on 2025-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0007_creditrequest_created_at_credittransfer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='total_credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
